routes/web.php
<?php

use App\Http\Controllers\AssetController;
use App\Http\Controllers\CollectionController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\UploadController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('collections.index');
})->name('home.index');

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/collections', [CollectionController::class, 'index'])->name('collections.index');
    Route::get('/collections/{collection}', [CollectionController::class, 'show'])->name('collections.show');
    Route::delete('/collections/{collection}', [CollectionController::class, 'destroy'])->name('collections.destroy');

    Route::get('/upload', [UploadController::class, 'index'])->name('upload.index');
    Route::post('/upload', [UploadController::class, 'store'])->name('upload.store');
    Route::post('/upload/complete', [UploadController::class, 'complete'])->name('upload.complete');
    Route::delete('/upload', [UploadController::class, 'destroy'])->name('upload.destroy');

    Route::get('/assets/{asset}', [AssetController::class, 'show'])->name('assets.show');
    Route::put('/assets/{asset}', [AssetController::class, 'update'])->name('assets.update');
    Route::delete('/asset/{asset}', [AssetController::class, 'destroy'])->name('assets.destroy');
    Route::put('/assets/{asset}/rotate', [AssetController::class, 'rotate'])->name('assets.rotate');
    Route::post('/assets/process/{asset}', [AssetController::class, 'process'])->name('assets.process');

    Route::get('/tags', [TagController::class, 'index'])->name('tags.index');
    Route::get('/tags/{tag}', [TagController::class, 'show'])->name('tags.show');

    Route::get('invite', [UserController::class, 'invite'])->name('users.invite');
    Route::post('invite', [UserController::class, 'sendInvite'])->name('users.send_invite');

    Route::resource('users', UserController::class);
});

require __DIR__ . '/auth.php';

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasApiTokens, HasFactory, Notifiable;

    const ROLE_ADMIN = 'admin';

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'invitation_token',
        'invited_at',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'created_at' => 'datetime',
        'invited_at' => 'datetime',
    ];

    public function collections()
    {
        return $this->belongsToMany(Collection::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Mail\InviteCreated;
use App\Models\Collection;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;

class UserController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(User::class, 'user');
    }

    public function index()
    {
        $users = User::orderBy('name')->get();

        return view('users.index', [
            'users' => $users,
        ]);
    }

    public function edit(User $user)
    {
        $collections = Collection::all()
            ->sortBy('name');

        return view('users.edit', [
            'user' => $user,
            'collections' => $collections,
        ]);
    }

    public function update(Request $request, User $user)
    {
        $request->validate([
            'name' => 'required',
            'email' => 'required|email',
            'role' => [Rule::in('', User::ROLE_ADMIN)],
        ]);

        if ($request->filled('name')) {
            $user->name = $request->name;
        }
        if ($request->filled('email')) {
            $user->email = $request->email;
        }
        if ($request->filled('role')) {
            $user->role = $request->role;
        } else {
            $user->role = null;
        }

        $user->collections()->detach();
        if ($request->filled('collections')) {
            foreach ($request->collections as $collectionId) {
                $collection = Collection::find($collectionId);
                if ($collection) {
                    $user->collections()->attach($collection);
                }
            }
        }

        $user->save();

        return redirect()->route('users.edit', $user);
    }

    public function destroy(User $user)
    {
        $user->delete();

        return redirect()->route('users.index');
    }

    public function invite()
    {
        $collections = Collection::all()
            ->sortBy('name');

        return view('users.invite', [
            'collections' => $collections,
        ]);
    }

    public function sendInvite(Request $request)
    {
        $request->validate([
            'email' => 'required|email',
            'collections' => 'required',
        ]);

        $user = User::create([
            'name' => $request->email,
            'email' => $request->email,
            'invitation_token' => Str::random(32),
            'invited_at' => Carbon::now(),
            'password' => Str::random(255),
        ]);

        if ($request->filled('collections')) {
            foreach ($request->collections as $collectionId) {
                $collection = Collection::find($collectionId);
                if ($collection) {
                    $user->collections()->attach($collection);
                }
            }
        }
        $user->save();

        Mail::to($user->email)->send(new InviteCreated($user));

        return redirect()->route('users.index');
    }
}

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('title', "User {$user->name}")

@section('content')

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><i class="bi bi-house"></i> <a href="{{ route('collections.index') }}">{{ __('nav.home') }}</a></li>
            <li class="breadcrumb-item"><a href="{{ route('users.index') }}">{{ __('nav.users') }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ $user->name }}</li>
        </ol>
    </nav>

    <h1>{{ $user->name }}</h1>

    <form action="{{ route('users.update', $user) }}" method="post" class="mt-3">
        @csrf
        @method('PUT')

        <div class="row mb-3">
            <label for="name" class="form-label col-md-4 text-md-end">Name</label>
            <div class="col-md-5">
                <input type="name" class="form-control @error('name') is-invalid @enderror" id="name" name="name"
                    value="{{ old('name', $user->name) }}" autofocus required>

                @error('name')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>

        <div class="row mb-3">
            <label for="email" class="form-label col-md-4 text-md-end">Email address</label>
            <div class="col-md-5">
                <input type="email" class="form-control @error('email') is-invalid @enderror" id="email" name="email"
                    value="{{ old('email', $user->email) }}" autofocus required>

                @error('email')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>

        <div class="row mb-3">
            <label for="role" class="form-label col-md-4 text-md-end">Role</label>
            <div class="col-md-5">
                <select class="form-select @error('role') is-invalid @enderror" id="role" name="role">
                    <option value="" @if ($user->role === null) selected @endif>-</option>
                    <option value="admin" @if ($user->role === 'admin') selected @endif>Administrator</option>
                </select>

                @error('role')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>

        @if ($user->role !== App\Models\User::ROLE_ADMIN)
            <div class="row mb-3">
                <label for="collections" class="form-label col-md-4 text-md-end">Collections</label>
                <div class="col-md-5">
                    <select class="form-select @error('collection') is-invalid @enderror" id="collections" name="collections[]" multiple>
                        @foreach ($collections as $collection)
                            <option value="{{ $collection->id }}" @if ($user->collections->contains($collection)) selected @endif>{{ $collection->name }}</option>
                        @endforeach
                    </select>

                    @error('collections')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
            </div>
        @endif

        <div class="row mb-0">
            <div class="col-md-8 offset-md-4">
                <button type="submit" class="btn btn-success">Save</button>

                <a class="btn btn-link" href="{{ route('users.index') }}">
                    Cancel
                </a>
            </div>
        </div>

    </form>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('title', 'Users')

@section('content')

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><i class="bi bi-house"></i> <a href="{{ route('collections.index') }}">{{ __('nav.home') }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ __('nav.users') }}</li>
        </ol>
    </nav>

    <h1>Users</h1>

    <a class="btn btn-primary float-end" href="{{ route('users.invite') }}">Invite someone</a>

    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Role</th>
                <th>Created</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach ($users as $user)
                <tr>
                    <td>
                        <a href="{{ route('users.edit', $user) }}">
                            {{ $user->name }}
                        </a>
                        @if ($user->invitation_token)
                            <span class="ms-2 text-warning">
                                <i class="bi bi-card-heading"></i> Invite sent {{ $user->invited_at }}
                            </span>
                        @endif
                    </td>
                    <td>{{ $user->email }}</td>
                    <td>{{ $user->role ?? '-' }}</td>
                    <td>{{ $user->created_at }}</td>
                    <th>
                        <form action="{{ route('users.destroy', $user) }}" method="post"
                            onsubmit="javascript:return confirm('This user will be deleted');">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-link">
                                <i class="bi bi-trash text-danger"></i>
                            </button>
                        </form>
                    </th>
                </tr>
            @endforeach
        </tbody>
    </table>
@endsection

resources/views/users/invite.blade.php
@extends('layouts.app')

@section('title', "Invite someone")

@section('content')

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><i class="bi bi-house"></i> <a href="{{ route('collections.index') }}">{{ __('nav.home') }}</a></li>
            <li class="breadcrumb-item"><a href="{{ route('users.index') }}">{{ __('nav.users') }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">Invite someone</li>
        </ol>
    </nav>

    <h1>Invite someone</h1>

    <form action="{{ route('users.send_invite') }}" method="post" class="mt-3">
        @csrf
        @method('POST')

        <div class="row mb-3">
            <label for="email" class="form-label col-md-4 text-md-end">Email address</label>
            <div class="col-md-5">
                <input type="email" class="form-control @error('email') is-invalid @enderror" id="email" name="email"
                    value="{{ old('email') }}" autofocus required>

                @error('email')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>


        <div class="row mb-3">
            <label for="collections" class="form-label col-md-4 text-md-end">Collections</label>
            <div class="col-md-5">
                <select class="form-select @error('collection') is-invalid @enderror" id="collections" name="collections[]" required multiple>
                    @foreach ($collections as $collection)
                        <option value="{{ $collection->id }}">{{ $collection->name }}</option>
                    @endforeach
                </select>

                @error('collections')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>


        <div class="row mb-0">
            <div class="col-md-8 offset-md-4">
                <button type="submit" class="btn btn-success">Send invite</button>

                <a class="btn btn-link" href="{{ route('users.index') }}">
                    Cancel
                </a>
            </div>
        </div>

    </form>
@endsection