routes/web.php
<?php

use App\Http\Controllers\AssetController;
use App\Http\Controllers\CollectionController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\UploadController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('collections.index');
})->name('home.index');

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/collections', [CollectionController::class, 'index'])->name('collections.index');
    Route::get('/collections/{collection}', [CollectionController::class, 'show'])->name('collections.show');
    Route::delete('/collections/{collection}', [CollectionController::class, 'destroy'])->name('collections.destroy');

    Route::get('/upload', [UploadController::class, 'index'])->name('upload.index');
    Route::post('/upload', [UploadController::class, 'store'])->name('upload.store');
    Route::post('/upload/complete', [UploadController::class, 'complete'])->name('upload.complete');
    Route::delete('/upload', [UploadController::class, 'destroy'])->name('upload.destroy');

    Route::get('/assets/{asset}', [AssetController::class, 'show'])->name('assets.show');
    Route::put('/assets/{asset}', [AssetController::class, 'update'])->name('assets.update');
    Route::delete('/asset/{asset}', [AssetController::class, 'destroy'])->name('assets.destroy');
    Route::put('/assets/{asset}/rotate', [AssetController::class, 'rotate'])->name('assets.rotate');
    Route::post('/assets/process/{asset}', [AssetController::class, 'process'])->name('assets.process');

    Route::get('/tags', [TagController::class, 'index'])->name('tags.index');
    Route::get('/tags/{tag}', [TagController::class, 'show'])->name('tags.show');

    Route::get('invite', [UserController::class, 'invite'])->name('users.invite');
    Route::post('invite', [UserController::class, 'sendInvite'])->name('users.send_invite');

    Route::resource('users', UserController::class);
});

require __DIR__ . '/auth.php';

app/Models/Asset.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Asset extends Model
{
    use HasFactory;

    const PATH_ORIGINALS = 'originals';
    const PATH_THUMBNAILS = 'thumbnails';

    protected $fillable = [
        'name', 'extension', 'description',
        'location', 'datetime', 'date',
    ];

    protected $casts = [
        'datetime' => 'datetime',
        'processed' => 'boolean',
    ];

    public function collection()
    {
        return $this->belongsTo(Collection::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    public function processLog()
    {
        return $this->hasOne(ProcessLog::class);
    }

    public function getBasenameAttribute()
    {
        return str_pad($this->id, 12, '0', STR_PAD_LEFT);
    }

    public function getFilenameAttribute()
    {
        return $this->basename . '.' . strtolower($this->extension);
    }

    public function getStoragePath()
    {
        $id = str_pad($this->id, 12, '0', STR_PAD_LEFT);
        $chunks = str_split($id, 3);

        return join('/', [
            $chunks[0],
            $chunks[1],
            $chunks[2],
            $this->filename,
        ]);
    }

    public function getOriginalPathAttribute()
    {
        return Asset::PATH_ORIGINALS . '/' . $this->getStoragePath();
    }

    public function getThumbnailPathAttribute()
    {
        return Asset::PATH_THUMBNAILS . '/' . $this->getStoragePath();
    }

    public function getThumbnailUrlAttribute()
    {
        if ($this->processed) {
            return asset('storage/' . $this->thumbnail_path);
        } else {
            return '/img/placeholder.png';
        }
    }
}

app/Models/Collection.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Collection extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'extension'];

    public function assets()
    {
        return $this->hasMany(Asset::class);
    }

    public function users()
    {
        return $this->belongsToMany(User::class);
    }
}

app/Http/Controllers/CollectionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Asset;
use App\Models\Collection;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class CollectionController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Collection::class, 'collection');
    }

    public function index(Request $request)
    {
        $assets = Asset::whereNull('collection_id')->get();

        $collections = Auth::user()->collections
            ->sortBy('name');

        if (Auth::user()->role === User::ROLE_ADMIN) {
            $collections = Collection::all()
                ->sortBy('name');
        }

        return view('collections.index', [
            'assets' => $assets,
            'collections' => $collections,
        ]);
    }

    public function show(Collection $collection)
    {
        $assets = Asset::where('collection_id', '=', $collection->id)
            ->orderBy('name')
            ->paginate(20);

        return view('collections.show', [
            'collection' => $collection,
            'assets'     => $assets,
        ]);
    }

    public function destroy(Collection $collection)
    {
        $collection->assets->each(function ($asset) {
            Storage::disk('public')->delete($asset->original_path);
            Storage::disk('public')->delete($asset->thumbnail_path);
            $asset->delete();
        });
        $collection->delete();

        return redirect()->route('collections.index');
    }
}

resources/views/collections/index.blade.php
@extends('layouts.app')

@section('title', "Collections")

@section('content')

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page"><i class="bi bi-house"></i> {{ __('nav.home') }}</li>
        </ol>
    </nav>

    <h1>{{ trans_choice('collections.collection_count', $collections->count()) }}</h1>

    <div class="mt-1 row row-cols-1 row-cols-sm-2 row-cols-xl-4 g-3">
        @foreach ($collections as $collection)
            @can('view', $collection)
                <div class="col d-flex">
                    <div class="card w-100">
                        @if ($collection->assets->isNotEmpty())
                            <a href="{{ route('collections.show', $collection) }}">
                                <img src="{{ $collection->assets->sortBy('name')->first()->thumbnail_url }}?ts={{ microtime(true) }}"
                                    class="card-img-top" alt="{{ $collection->name }}">
                            </a>
                        @endif
                        <div class="card-body">
                            <h5 class="card-title">{{ $collection->name }}</h5>
                            <p class="card-text">
                                {{ trans_choice('collections.photo_count', $collection->assets->count()) }}

                                @if ($collection->assets->pluck('processed')->contains(false))
                                    <i class="bi bi-exclamation-triangle-fill text-warning"></i>
                                @endif
                            </p>
                            <a href="{{ route('collections.show', $collection) }}">{{ __('collections.view') }}</a>
                        </div>
                    </div>
                </div>
            @endcan
        @endforeach
    </div>


@endsection

resources/views/collections/show.blade.php
@extends('layouts.app')

@section('title', "Collection {$collection->name}")

@section('content')

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><i class="bi bi-house"></i> <a href="{{ route('collections.index') }}">{{ __('nav.home') }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ $collection->name }}</li>
        </ol>
    </nav>

    <form action="{{ route('collections.destroy', $collection) }}" method="post"
        onsubmit="javascript:return confirm('This collection and all assets will be permanently deleted');">
        @method('DELETE')
        @csrf
        <h1>
            {{ $collection->name }}

            @can('delete', $collection)
                <button type="submit" class="btn btn-link text-danger">
                    <i class="bi bi-trash"></i>
                </button>
            @endcan
        </h1>
    </form>

    {{ $assets->links() }}
    <hr>

    <div class="mt-1 row row-cols-1 row-cols-sm-2 row-cols-xl-4 g-3">
        @foreach ($assets as $asset)
            @can('view', $asset)
                <div class="col d-flex">
                    @include('assets.partial-list', ['asset' => $asset])
                </div>
            @endcan
        @endforeach
    </div>

    <hr>
    {{ $assets->links() }}

@endsection